-- Pronostix v2 - candidatos a especiales Mundial FIFA 2026
-- Fuente preferida: FIFA confirmó 1,248 jugadores en 48 selecciones.
-- Este seed NO intenta cargar los 1,248 jugadores completos: carga 3 candidatos de campo y 1 portero por selección para especiales.
-- Requiere ejecutar antes sql/seed_worldcup_2026.sql para que existan tournament y teams.
-- No toca teams, matches, tournaments ni schema. Solo inserta/actualiza public.players.
-- Compatible con editores SQL que ejecutan sentencias en sesiones separadas: no usa tablas temporales.

begin;

update public.players
set is_special_candidate = false
where tournament_id = '20260000-0000-0000-0000-000000000001';

with pronostix_wc2026_player_seed(team_code, player_name, position) as (
  values
('MEX', 'Julián Quiñones', 'FIELD'),
('MEX', 'Raúl Jiménez', 'FIELD'),
('MEX', 'Roberto Alvarado', 'FIELD'),
('MEX', 'Raúl Rangel', 'GK'),
('RSA', 'Lyle Foster', 'FIELD'),
('RSA', 'Percy Tau', 'FIELD'),
('RSA', 'Evidence Makgopa', 'FIELD'),
('RSA', 'Ronwen Williams', 'GK'),
('KOR', 'Son Heung-min', 'FIELD'),
('KOR', 'Hwang Hee-chan', 'FIELD'),
('KOR', 'Lee Kang-in', 'FIELD'),
('KOR', 'Jo Hyeon-woo', 'GK'),
('CZE', 'Patrik Schick', 'FIELD'),
('CZE', 'Adam Hložek', 'FIELD'),
('CZE', 'Tomáš Souček', 'FIELD'),
('CZE', 'Matěj Kovář', 'GK'),
('CAN', 'Jonathan David', 'FIELD'),
('CAN', 'Alphonso Davies', 'FIELD'),
('CAN', 'Cyle Larin', 'FIELD'),
('CAN', 'Maxime Crépeau', 'GK'),
('BIH', 'Edin Džeko', 'FIELD'),
('BIH', 'Ermedin Demirović', 'FIELD'),
('BIH', 'Amar Dedić', 'FIELD'),
('BIH', 'Ibrahim Šehić', 'GK'),
('QAT', 'Akram Afif', 'FIELD'),
('QAT', 'Almoez Ali', 'FIELD'),
('QAT', 'Hassan Al-Haydos', 'FIELD'),
('QAT', 'Meshaal Barsham', 'GK'),
('SUI', 'Breel Embolo', 'FIELD'),
('SUI', 'Xherdan Shaqiri', 'FIELD'),
('SUI', 'Dan Ndoye', 'FIELD'),
('SUI', 'Yann Sommer', 'GK'),
('BRA', 'Vinícius Júnior', 'FIELD'),
('BRA', 'Rodrygo', 'FIELD'),
('BRA', 'Endrick', 'FIELD'),
('BRA', 'Alisson Becker', 'GK'),
('MAR', 'Youssef En-Nesyri', 'FIELD'),
('MAR', 'Achraf Hakimi', 'FIELD'),
('MAR', 'Brahim Díaz', 'FIELD'),
('MAR', 'Yassine Bounou', 'GK'),
('HAI', 'Frantzdy Pierrot', 'FIELD'),
('HAI', 'Duckens Nazon', 'FIELD'),
('HAI', 'Carnejy Antoine', 'FIELD'),
('HAI', 'Johny Placide', 'GK'),
('SCO', 'Scott McTominay', 'FIELD'),
('SCO', 'Che Adams', 'FIELD'),
('SCO', 'John McGinn', 'FIELD'),
('SCO', 'Angus Gunn', 'GK'),
('USA', 'Christian Pulisic', 'FIELD'),
('USA', 'Folarin Balogun', 'FIELD'),
('USA', 'Ricardo Pepi', 'FIELD'),
('USA', 'Matt Turner', 'GK'),
('PAR', 'Miguel Almirón', 'FIELD'),
('PAR', 'Julio Enciso', 'FIELD'),
('PAR', 'Ramón Sosa', 'FIELD'),
('PAR', 'Roberto Fernández', 'GK'),
('AUS', 'Mitchell Duke', 'FIELD'),
('AUS', 'Kusini Yengi', 'FIELD'),
('AUS', 'Craig Goodwin', 'FIELD'),
('AUS', 'Mathew Ryan', 'GK'),
('TUR', 'Hakan Çalhanoğlu', 'FIELD'),
('TUR', 'Arda Güler', 'FIELD'),
('TUR', 'Kenan Yıldız', 'FIELD'),
('TUR', 'Uğurcan Çakır', 'GK'),
('CIV', 'Sébastien Haller', 'FIELD'),
('CIV', 'Simon Adingra', 'FIELD'),
('CIV', 'Franck Kessié', 'FIELD'),
('CIV', 'Yahia Fofana', 'GK'),
('ECU', 'Enner Valencia', 'FIELD'),
('ECU', 'Moisés Caicedo', 'FIELD'),
('ECU', 'Kendry Páez', 'FIELD'),
('ECU', 'Hernán Galíndez', 'GK'),
('GER', 'Jamal Musiala', 'FIELD'),
('GER', 'Florian Wirtz', 'FIELD'),
('GER', 'Kai Havertz', 'FIELD'),
('GER', 'Manuel Neuer', 'GK'),
('CUW', 'Juninho Bacuna', 'FIELD'),
('CUW', 'Rangelo Janga', 'FIELD'),
('CUW', 'Gervane Kastaneer', 'FIELD'),
('CUW', 'Eloy Room', 'GK'),
('NED', 'Cody Gakpo', 'FIELD'),
('NED', 'Memphis Depay', 'FIELD'),
('NED', 'Xavi Simons', 'FIELD'),
('NED', 'Bart Verbruggen', 'GK'),
('JPN', 'Takumi Minamino', 'FIELD'),
('JPN', 'Ritsu Doan', 'FIELD'),
('JPN', 'Takefusa Kubo', 'FIELD'),
('JPN', 'Zion Suzuki', 'GK'),
('SWE', 'Alexander Isak', 'FIELD'),
('SWE', 'Viktor Gyökeres', 'FIELD'),
('SWE', 'Dejan Kulusevski', 'FIELD'),
('SWE', 'Robin Olsen', 'GK'),
('TUN', 'Elias Achouri', 'FIELD'),
('TUN', 'Youssef Msakni', 'FIELD'),
('TUN', 'Seifeddine Jaziri', 'FIELD'),
('TUN', 'Bechir Ben Saïd', 'GK'),
('IRN', 'Mehdi Taremi', 'FIELD'),
('IRN', 'Sardar Azmoun', 'FIELD'),
('IRN', 'Alireza Jahanbakhsh', 'FIELD'),
('IRN', 'Alireza Beiranvand', 'GK'),
('NZL', 'Chris Wood', 'FIELD'),
('NZL', 'Sarpreet Singh', 'FIELD'),
('NZL', 'Kosta Barbarouses', 'FIELD'),
('NZL', 'Max Crocombe', 'GK'),
('BEL', 'Romelu Lukaku', 'FIELD'),
('BEL', 'Kevin De Bruyne', 'FIELD'),
('BEL', 'Jérémy Doku', 'FIELD'),
('BEL', 'Thibaut Courtois', 'GK'),
('EGY', 'Mohamed Salah', 'FIELD'),
('EGY', 'Omar Marmoush', 'FIELD'),
('EGY', 'Mostafa Mohamed', 'FIELD'),
('EGY', 'Mohamed El Shenawy', 'GK'),
('KSA', 'Salem Al-Dawsari', 'FIELD'),
('KSA', 'Firas Al-Buraikan', 'FIELD'),
('KSA', 'Saleh Al-Shehri', 'FIELD'),
('KSA', 'Mohammed Al-Owais', 'GK'),
('URU', 'Darwin Núñez', 'FIELD'),
('URU', 'Federico Valverde', 'FIELD'),
('URU', 'Facundo Pellistri', 'FIELD'),
('URU', 'Sergio Rochet', 'GK'),
('ESP', 'Lamine Yamal', 'FIELD'),
('ESP', 'Álvaro Morata', 'FIELD'),
('ESP', 'Nico Williams', 'FIELD'),
('ESP', 'Unai Simón', 'GK'),
('CPV', 'Ryan Mendes', 'FIELD'),
('CPV', 'Garry Rodrigues', 'FIELD'),
('CPV', 'Bebé', 'FIELD'),
('CPV', 'Vozinha', 'GK'),
('FRA', 'Kylian Mbappé', 'FIELD'),
('FRA', 'Ousmane Dembélé', 'FIELD'),
('FRA', 'Antoine Griezmann', 'FIELD'),
('FRA', 'Mike Maignan', 'GK'),
('SEN', 'Sadio Mané', 'FIELD'),
('SEN', 'Nicolas Jackson', 'FIELD'),
('SEN', 'Ismaïla Sarr', 'FIELD'),
('SEN', 'Édouard Mendy', 'GK'),
('IRQ', 'Aymen Hussein', 'FIELD'),
('IRQ', 'Ali Jasim', 'FIELD'),
('IRQ', 'Mohanad Ali', 'FIELD'),
('IRQ', 'Jalal Hassan', 'GK'),
('NOR', 'Erling Haaland', 'FIELD'),
('NOR', 'Martin Ødegaard', 'FIELD'),
('NOR', 'Alexander Sørloth', 'FIELD'),
('NOR', 'Ørjan Nyland', 'GK'),
('ARG', 'Lionel Messi', 'FIELD'),
('ARG', 'Lautaro Martínez', 'FIELD'),
('ARG', 'Julián Álvarez', 'FIELD'),
('ARG', 'Emiliano Martínez', 'GK'),
('ALG', 'Riyad Mahrez', 'FIELD'),
('ALG', 'Amine Gouiri', 'FIELD'),
('ALG', 'Baghdad Bounedjah', 'FIELD'),
('ALG', 'Anthony Mandrea', 'GK'),
('AUT', 'Marko Arnautović', 'FIELD'),
('AUT', 'Michael Gregoritsch', 'FIELD'),
('AUT', 'Marcel Sabitzer', 'FIELD'),
('AUT', 'Patrick Pentz', 'GK'),
('JOR', 'Mousa Al-Taamari', 'FIELD'),
('JOR', 'Yazan Al-Naimat', 'FIELD'),
('JOR', 'Ali Olwan', 'FIELD'),
('JOR', 'Yazeed Abulaila', 'GK'),
('POR', 'Cristiano Ronaldo', 'FIELD'),
('POR', 'Rafael Leão', 'FIELD'),
('POR', 'Gonçalo Ramos', 'FIELD'),
('POR', 'Diogo Costa', 'GK'),
('COD', 'Cédric Bakambu', 'FIELD'),
('COD', 'Yoane Wissa', 'FIELD'),
('COD', 'Silas', 'FIELD'),
('COD', 'Lionel Mpasi', 'GK'),
('UZB', 'Eldor Shomurodov', 'FIELD'),
('UZB', 'Abbosbek Fayzullaev', 'FIELD'),
('UZB', 'Jaloliddin Masharipov', 'FIELD'),
('UZB', 'Utkir Yusupov', 'GK'),
('COL', 'Luis Díaz', 'FIELD'),
('COL', 'James Rodríguez', 'FIELD'),
('COL', 'Jhon Durán', 'FIELD'),
('COL', 'Camilo Vargas', 'GK'),
('GHA', 'Mohammed Kudus', 'FIELD'),
('GHA', 'Iñaki Williams', 'FIELD'),
('GHA', 'Jordan Ayew', 'FIELD'),
('GHA', 'Lawrence Ati-Zigi', 'GK'),
('PAN', 'José Fajardo', 'FIELD'),
('PAN', 'Ismael Díaz', 'FIELD'),
('PAN', 'Cecilio Waterman', 'FIELD'),
('PAN', 'Orlando Mosquera', 'GK'),
('ENG', 'Harry Kane', 'FIELD'),
('ENG', 'Jude Bellingham', 'FIELD'),
('ENG', 'Phil Foden', 'FIELD'),
('ENG', 'Jordan Pickford', 'GK'),
('CRO', 'Andrej Kramarić', 'FIELD'),
('CRO', 'Luka Modrić', 'FIELD'),
('CRO', 'Ivan Perišić', 'FIELD'),
('CRO', 'Dominik Livaković', 'GK')
)
insert into public.players(tournament_id, team_id, name, position, is_special_candidate)
select
  '20260000-0000-0000-0000-000000000001'::uuid as tournament_id,
  t.id as team_id,
  ps.player_name as name,
  ps.position as position,
  true as is_special_candidate
from pronostix_wc2026_player_seed ps
join public.teams t
  on t.tournament_id = '20260000-0000-0000-0000-000000000001'
 and t.code = ps.team_code
on conflict (tournament_id, name) do update set
  team_id = excluded.team_id,
  name = excluded.name,
  position = excluded.position,
  is_special_candidate = excluded.is_special_candidate;

commit;

-- Validaciones esperadas:
-- Total jugadores insertados:
-- select count(*) from public.players where tournament_id = '20260000-0000-0000-0000-000000000001' and is_special_candidate; -- 192
-- Jugadores por selección:
-- select t.code, t.name, count(p.id) as players_count
-- from public.teams t
-- left join public.players p on p.team_id = t.id and p.is_special_candidate
-- where t.tournament_id = '20260000-0000-0000-0000-000000000001'
-- group by t.code, t.name
-- order by t.code; -- 4 por selección
-- Validación de team_id:
-- select count(*) as players_without_team
-- from public.players
-- where tournament_id = '20260000-0000-0000-0000-000000000001'
--   and team_id is null; -- 0
